# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 98e9a7ec7627dfb0c29a478ca058cdcc8711734e3c80b23a1e8ea2a5bc2a5e98f638367b0b51de7f6759b5683f0ef3e7e05767ead4376b41e1d5fb749841c65c

test:
  secret_key_base: 4dc5cac15815519bdb99d172daab61b7973eabbb21398faef1ec949beb032b1b36482179b256902ad8f7a86697a1cc0dd0eca9f5b2e8fdaf62385cb3341c99ed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
